name: Crowdin Action

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_EXISTS: ${{ steps.check_branch.outputs.BRANCH_EXISTS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          skip_untranslated_files: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'main'
          pull_request_labels: 'i18n'
          config: '.crowdin.yml'
        env:
          # A classic GitHub Personal Access Token with the 'repo' scope selected (the user should have write access to the repository).
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # A numeric ID, found at https://crowdin.com/project/<projectName>/tools/api
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}

          # Visit https://crowdin.com/settings#api-key to create this token
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - name: Check for l10n_crowdin_translations branch
        id: check_branch
        run: |
          branch_exists=$(git ls-remote origin refs/heads/l10n_crowdin_translations | grep -q refs/heads/l10n_crowdin_translations && echo true || echo false)
          echo "BRANCH_EXISTS=${branch_exists}" >> $GITHUB_OUTPUT

  update-i18n:
    needs: synchronize-with-crowdin
    runs-on: ubuntu-latest
    if: ${{ needs.synchronize-with-crowdin.outputs.BRANCH_EXISTS == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: l10n_crowdin_translations

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --force

      - name: Update i18n.ts
        run: node .github/workflows/l10ncheck.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/locales/i18n.ts
          git add src/app/page.tsx
          git commit -m "Update i18n.ts with new languages" || echo "Nothing to commit."
          git push
